-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [borrowed_multidim_array]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace borrowed_multidim_array

/-- [borrowed_multidim_array::f]:
    Source: 'tests/src/borrowed-multidim-array.rs', lines 8:0-14:1
    Visibility: public -/
def f (_i : Array (Array Std.U8 10#usize) 10#usize) : Result Std.Usize := do
  ok 0#usize

/-- [borrowed_multidim_array::g]:
    Source: 'tests/src/borrowed-multidim-array.rs', lines 16:0-18:1
    Visibility: public -/
def g (i : Array Std.U8 2#usize) : Result Std.U8 := do
  Array.index_usize i 0#usize

/-- [borrowed_multidim_array::h]:
    Source: 'tests/src/borrowed-multidim-array.rs', lines 20:0-22:1
    Visibility: public -/
def h (i : (Std.U8 × Std.U8)) : Result Std.U8 := do
  let (i1, i2) := i
  i1 + i2

end borrowed_multidim_array
